package at.specure.data.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import at.specure.data.Classification
import at.specure.data.Columns
import at.specure.data.Tables
import at.specure.result.QoECategory

@Entity(tableName = Tables.QOE)
data class QoeInfoRecord(

    /**
     * id for internal purpose of the local DB
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Test uuid generated by control server - unique identification of the test
     */
    @ForeignKey(
        entity = TestResultRecord::class,
        parentColumns = [Columns.TEST_UUID_PARENT_COLUMN],
        childColumns = ["testUUID"],
        onDelete = ForeignKey.CASCADE
    )
    val testUUID: String,

    /**
     * Category of the qoe
     */
    val category: QoECategory,

    /**
     * Classification sent by server
     */
    val classification: Classification,

    /**
     * Percentage in decimal number in [0.0, 1.0] interval
     */
    val percentage: Float
)