package at.specure.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import at.specure.data.Tables
import at.specure.result.QoSCategory

@Entity(
    tableName = Tables.QOS_TEST_GOAL
)
data class QosTestGoalRecord(

    /**
     * id for internal purpose of the local DB
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Test uuid generated by control server - unique identification of the test
     */
    val testUUID: String,

    /**
     * Id of the qos test
     */
    val qosTestId: Long,

    /**
     * Category of the qos
     */
    val category: QoSCategory,

    /**
     * Localized test summary text
     */
    val description: String,

    /**
     * Language code of test description localization
     */
    val language: String,

    /**
     * Is test successful?
     */
    val success: Boolean
)