package at.specure.data.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import at.specure.data.Columns
import at.specure.data.Tables
import at.specure.result.QoSCategory

@Entity(
    tableName = Tables.QOS_TEST_RESULT_ITEM,
    foreignKeys = [
        ForeignKey(
            entity = TestResultRecord::class,
            parentColumns = [Columns.TEST_UUID_PARENT_COLUMN],
            childColumns = ["testUUID"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [ Index(value=["qosTestId"], unique = true) ]
)
data class QosTestItemRecord(

    /**
     * id for internal purpose of the local DB
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Test uuid generated by control server - unique identification of the test
     */
    val testUUID: String,

    /**
     * Id of the qos test
     */
    val qosTestId: Long,

    /**
     * Category of the qos
     */
    val category: QoSCategory,

    /**
     * Test number inside the one test category
     */
    val testNumber: Int,

    /**
     * Localized test summary text
     */
    val testSummary: String,

    /**
     * Localized test description text
     */
    val testDescription: String,

    /**
     * Language code of test description localization
     */
    val language: String,

    /**
     * Is test successful?
     */
    val success: Boolean,

    /**
     * duration in nanoseconds
     */
    val durationNanos: Long?,

    /**
     * start time nanoseconds, relative to start of the test
     */
    val startTimeNanos: Long?
)