package at.specure.test

import at.rtr.rmbt.client.RMBTClientCallback

interface TestController {

    val testUUID: String?

    val isRunning: Boolean

    val testStartTimeNanos: Long

    /**
     * loopModeUUID is loop uuid generated by the server side, used to obtain new test and send test to the server
     * loopLocalUUID is loop uuid generated on the client for purposes of the client, necessary when there is no signal during first measurements of the loop mode, because we does not obtain uuid from server
     */
    fun start(
        deviceInfo: DeviceInfo,
        loopModeUUID: String?,
        loopLocalUUID: String?,
        loopTestCount: Int,
        listener: TestProgressListener,
        clientCallback: RMBTClientCallback
    )

    fun stop()

    /**
     * Stops all threads and clients. All values will be reset to default ones
     */
    fun reset()
}